import { BadRequestException, Injectable } from '@nestjs/common'; import { Prisma } from '@prisma/client'; import { PrismaService } from '../../../prisma/prisma.service'; import { DateRangeQueryDto, InventoryReportQueryDto, ProductsReportQueryDto, SalesReportQueryDto } from './dto/report-queries.dto';
@Injectable() export class ReportsService {
  constructor(private readonly prisma: PrismaService) {}
  private range(from: string, to: string) { const dateFrom = new Date(from); const dateTo = new Date(to); if (dateFrom > dateTo) throw new BadRequestException('dateFrom cannot be after dateTo'); return { gte: dateFrom, lte: dateTo }; }
  private optionalRange(from?: string, to?: string) { if (from && to) return this.range(from, to); return { ...(from ? { gte: new Date(from) } : {}), ...(to ? { lte: new Date(to) } : {}) }; }
  private period(date: Date, group: 'day' | 'week' | 'month') { const value = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate())); if (group === 'week') value.setUTCDate(value.getUTCDate() - ((value.getUTCDay() + 6) % 7)); if (group === 'month') value.setUTCDate(1); return value.toISOString().slice(0, 10); }
  async sales(query: SalesReportQueryDto) { const orders = await this.prisma.order.findMany({ where: { placedAt: this.range(query.dateFrom, query.dateTo), paymentStatus: { in: ['PAID', 'PARTIALLY_REFUNDED', 'REFUNDED'] } }, select: { placedAt: true, total: true } }); const values = new Map<string, { revenue: number; orderCount: number }>(); for (const order of orders) { const key = this.period(order.placedAt, query.groupBy); const point = values.get(key) ?? { revenue: 0, orderCount: 0 }; point.revenue += Number(order.total); point.orderCount++; values.set(key, point); } return { points: [...values].sort(([a], [b]) => a.localeCompare(b)).map(([period, value]) => ({ period, revenue: Number(value.revenue.toFixed(2)), orderCount: value.orderCount })) }; }
  async products(query: ProductsReportQueryDto) { const placedAt = this.optionalRange(query.dateFrom, query.dateTo); const sold = await this.prisma.orderItem.groupBy({ by: ['productId'], where: Object.keys(placedAt).length ? { order: { placedAt } } : undefined, _sum: { quantity: true, subtotal: true } }); const products = await this.prisma.product.findMany({ where: { deletedAt: null }, select: { id: true, title: true, variants: { where: { deletedAt: null }, select: { stockQty: true } } } }); const sales = new Map(sold.map(row => [row.productId, row])); const rows = products.map(product => ({ productId: product.id, title: product.title, unitsSold: sales.get(product.id)?._sum.quantity ?? 0, revenue: Number(sales.get(product.id)?._sum.subtotal ?? 0), stockQty: product.variants.reduce((sum, variant) => sum + variant.stockQty, 0) })); const sort = query.sort ?? 'best'; rows.sort((a, b) => sort === 'stock' ? a.stockQty - b.stockQty : sort === 'worst' ? a.unitsSold - b.unitsSold : b.unitsSold - a.unitsSold); return { rows }; }
  async customers(query: DateRangeQueryDto) { const range = this.range(query.dateFrom, query.dateTo); const newCustomers = await this.prisma.user.count({ where: { createdAt: range, deletedAt: null } }); const during = await this.prisma.order.findMany({ where: { placedAt: range, userId: { not: null } }, distinct: ['userId'], select: { userId: true } }); const ids = during.map(row => row.userId!).filter(Boolean); const prior = ids.length ? await this.prisma.order.findMany({ where: { userId: { in: ids }, placedAt: { lt: range.gte } }, distinct: ['userId'], select: { userId: true } }) : []; const spend = await this.prisma.order.groupBy({ by: ['userId'], where: { placedAt: range, userId: { not: null } }, _sum: { total: true }, _count: { id: true }, orderBy: { _sum: { total: 'desc' } }, take: 10 }); const users = await this.prisma.user.findMany({ where: { id: { in: spend.map(row => row.userId!).filter(Boolean) } }, select: { id: true, email: true, firstName: true, lastName: true } }); const byId = new Map(users.map(user => [user.id, user])); return { newCustomers, returningCustomers: prior.length, topSpenders: spend.map(row => ({ user: byId.get(row.userId!), totalSpent: Number(row._sum.total ?? 0), orderCount: row._count.id })) }; }
  async inventory(query: InventoryReportQueryDto) { const variants = await this.prisma.productVariant.findMany({ where: { deletedAt: null, product: { deletedAt: null } }, include: { product: true }, orderBy: { stockQty: 'asc' } }); return variants.filter(variant => variant.stockQty <= (query.threshold ?? variant.lowStockThreshold)); }
  async orders(query: DateRangeQueryDto) { const range = this.range(query.dateFrom, query.dateTo); const [statuses, payments] = await Promise.all([this.prisma.order.groupBy({ by: ['status'], where: { placedAt: range }, _count: { id: true } }), this.prisma.order.groupBy({ by: ['paymentStatus'], where: { placedAt: range }, _count: { id: true } })]); return { byStatus: Object.fromEntries(statuses.map(row => [row.status, row._count.id])), byPaymentStatus: Object.fromEntries(payments.map(row => [row.paymentStatus, row._count.id])) }; }
}
